name: "Build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          check-latest: true
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          add-job-summary: always
          cache-cleanup: on-success
          cache-read-only: ${{ github.ref != 'refs/heads/stable' }}

      - name: Execute build
        run: ./gradlew clean build --stacktrace
