name: Deploy Release to Plugin Portal

on:
  push:
    branches:
      - stable

jobs:
  deployRelease:
    environment: 'release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Publish to gradle plugin portal
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GPPORTALPUBLISHKEY }} -Pgradle.publish.secret=${{ secrets.GPPORTALPUBLISHSECRET }}
